import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

// const roboto = Roboto({ subsets: ["vietnamese"], weight: ['100', '300', '400', '500', '700', "900" ]});

const myFont = localFont(
    /*{
  src: './font/Roboto-Thin.ttf',
  display: 'swap'
}*/
    {
      src: [
        {
          path: './font/Roboto-Thin.ttf',
          weight: '100'
        },
        {
          path: './font/Roboto-Regular.ttf',
          weight: '400'
        }
      ],
      display: 'swap',
      variable: '--font-roboto'
    }
)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/*<body className={`${myFont.className} ${myFont.variable}`}>{children}</body>*/}
    <body className={`${myFont.variable}`}>{children}</body>
    </html>
  );
}
